### ISSUE TITLE
it does not work with 5.1

### ISSUE THREAD

**Issue by supernrm** [mayoz/pagination#1]
it does not work with 5.1 ;( maybe some update?

**Comment by verglas** [comment]
Not working for L5.0. links method has been removed.

**Comment by elling19** [comment]
:(
Not working for Laravel5.0. 
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Database\Eloquent\Collection' does not have a method 'links'

**Comment by mayoz** [comment]
Sorry, Laravel 5+ not supported custom service. Look this https://github.com/laravel/framework/issues/7510

If you have any ideas, please send PR.

**Comment by meiweijia** [comment]
How to use with lumen?  can not find 'Illuminate\Pagination\PaginationServiceProvider' in app.php

**Comment by mayoz** [comment]
@kubill not compatible with Lumen.
